site_name: SeaBee 的笔记合集
site_url: https://triplepiers.github.io/Notes_Collection/
copyright: Copyright © 2023-2025 SeaBee
repo_url: https://github.com/triplepiers/Notes_Collection
repo_name: Notes_Collection
theme:
  font: false                 # 禁止从 Google Fonts 加载
  favicon: images/favicon.svg # 标签页
  logo: images/favicon.svg    # topBar
  name: material
  palette:
    scheme: slate
    accent: amber
    primary: black
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/light-bulb-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs
    - navigation.footer
    - toc.follow
    - content.code.copy
extra_css:
  - stylesheets/extra.css
extra_javascript:
  # - javascripts/config.js
  - https://polyfill-fastly.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - statistics:
      ignore_languages:
        - mermaid
        - markdown
markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


# extra:
#   homepage: https://triplepiers.github.io/Notes_Collection/
nav:
- Home: index.md
- FrontEnd:
  - VSCode插件: Nulling/Front End/VSCodePlugin.md
  - Canvas: Nulling/Front End/Canvas.md
  - Animation:
      - GSAP: Nulling/Front End/Animations/GSAP.md
  - TailWindCSS: Nulling/Front End/TailWind.md
  - Type Script: Nulling/Front End/TS.md
  - Java Script:
    - 1 基础: Nulling/Front End/JS/基础.md
    - 2 对象与函数: Nulling/Front End/JS/对象与函数.md
    - 3 内置对象与正则: Nulling/Front End/JS/内置对象与正则.md
    - 4 DOM: Nulling/Front End/JS/DOM.md
    - 5 BOM: Nulling/Front End/JS/BOM.md
  - Vue2:
    - 1 HelloWorld: Nulling/Vue/Vue2/1 Intro.md
    - 2 组件: Nulling/Vue/Vue2/2 组件.md
    - 3 使用 Cli: Nulling/Vue/Vue2/3 使用Cli创建项目.md
    - 4 消息传递: Nulling/Vue/Vue2/4 消息传递.md
    - 5 网络请求: Nulling/Vue/Vue2/5 Ajax 网络请求.md
    - 6 第三方组件库: Nulling/Vue/Vue2/6 UI 组件库.md
  - Vue3: Nulling/Vue/Vue3.md
  - React:
    - 1 慢速上手: Nulling/React/慢速上手.md
    - 2 面向组件: Nulling/React/面向组件编程.md
    - 3 组件通信: Nulling/React/组件通信.md
    - 4 网络请求: Nulling/React/网络请求.md
    - 5 路由: Nulling/React/路由.md
    - 6 UI 组件库: Nulling/React/UI 组件库.md
  - WeChat:
    - 1 Intro: Nulling/Wechat App/Intro.md
    - 2 Template & Setting: Nulling/Wechat App/Template & Setting.md
    - 3 组件: Nulling/Wechat App/自定义组件 & 全局数据共享.md
  - Tips:
    - 布局: Nulling/Front End/布局.md
  - Tools:
    - WebSocket: Nulling/Tool/WebSocket.md
    - 测试:
      - Mccha: Nulling/Tool/Mocha.md
    - 异步请求:
      - Axios: Nulling/Tool/Axios.md
      - Promise: Nulling/Front End/Promise.md
    - NodeJS:
      - 1 火速上手: Nulling/Tool/NodeJS/1_Intro.md
      - 2 搓点项目: Nulling/Tool/NodeJS/2_Project.md
    - NextJS: Nulling/React/NextJS.md
- DataBase:
  - Mongo DB:
      - 1 快速上手: Nulling/Tool/MongoDB/快速上手.md
      - 2 慢速上头: Nulling/Tool/MongoDB/慢速上头.md
- 编程语言:
  - Python:
    - 1 Basic: Nulling/Python/1 Basic.md
    - 2-1 Project: Nulling/Python/2-1 Project.md
    - 2-2 Project: Nulling/Python/2-2 Project.md
  - Go:
    - 1 Basic: Nulling/Go/1 Basic.md
    - 2 面向对象: Nulling/Go/2 OOP.md
  - Rust:
    - 1 Basic: Nulling/Rust/1_init.md
    - 2 基础语法: Nulling/Rust/2_base.md
    - 3 项目实战: Nulling/Rust/3_project.md
- Agent:
  - LangChain: 
    - 1 Base: Nulling/Agent/LangChain/1_Base.md
    - 2 应用: Nulling/Agent/LangChain/2_Apps.md
  - Brainary: Nulling/Agent/Brainary.md
- Server: 
  - 1 基本环境: Nulling/Server/Base.md
  - 2 应用安装: Nulling/Server/Install_Apps.md
- 常用工具:
  - 常用项目创建: Nulling/Tool/常用项目创建.md
  - Git: Nulling/Tool/Git.md
  - Igem Uploads: Nulling/Tool/igem-uploads.md
- 软工课程:
  - 编译原理(旷工中):
    - 5 语法制导翻译: Nulling/编译原理/5 语法制导翻译.md
    - 6 中间代码生成: Nulling/编译原理/6 中间代码生成.md
    - 7 运行存储分配: Nulling/编译原理/7 运行存储分配.md
    - 8 代码优化: Nulling/编译原理/8 代码优化.md
    - 9 代码生成: Nulling/编译原理/9 代码生成.md
  - 计算机系统概论:
    - Chap 2 Bit, 数据类型与运算: Nulling/ICS/Chap 2 Bit, 数据类型与运算.md
    - Chap 3 数字逻辑: Nulling/ICS/Chap 3 数字逻辑.md